version: 2

sphinx:
   configuration: docs/conf.py

formats:
   - pdf
   - epub

python:
   version: 3.6
   install:
      - method: pip
        path: .
        extra_requirements:
            - docs
      - requirements: docs/requirements.txt
   system_packages: true